version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tgp

networks:
  tgp:
    external: true
    name: tgp