// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainings.Service.Repositories;

namespace Trainings.Service.Migrations
{
    [DbContext(typeof(TrainingsDbContext))]
    [Migration("20191123201140_ptg")]
    partial class ptg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Trainings.Service.Domain.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Trainings.Service.Domain.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76e03793-0a33-441e-94e7-dec64d1c9703"),
                            IdentityId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Test",
                            Surname = "Coach"
                        });
                });

            modelBuilder.Entity("Trainings.Service.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Trainings.Service.Domain.PlayerTrainingGroup", b =>
                {
                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainingGroupId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerTrainingGroup");
                });

            modelBuilder.Entity("Trainings.Service.Domain.TrainingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentOptionalChallenge")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Hour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("TrainingGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76e03793-0a33-441e-94e7-dec64d1c9703"),
                            CurrentOptionalChallenge = new Guid("00000000-0000-0000-0000-000000000000"),
                            Day = 3,
                            Hour = "18:00",
                            LevelName = "Red",
                            Name = "Wednesday 18:00"
                        });
                });

            modelBuilder.Entity("Trainings.Service.Domain.Attendance", b =>
                {
                    b.HasOne("Trainings.Service.Domain.TrainingGroup", "Group")
                        .WithMany("Attendances")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainings.Service.Domain.Player", b =>
                {
                    b.HasOne("Trainings.Service.Domain.Attendance", null)
                        .WithMany("AttendantPlayers")
                        .HasForeignKey("AttendanceId");
                });

            modelBuilder.Entity("Trainings.Service.Domain.PlayerTrainingGroup", b =>
                {
                    b.HasOne("Trainings.Service.Domain.Player", "Player")
                        .WithMany("PlayerTrainingGroups")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainings.Service.Domain.TrainingGroup", "TrainingGroup")
                        .WithMany("PlayerTrainingGroups")
                        .HasForeignKey("TrainingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainings.Service.Domain.TrainingGroup", b =>
                {
                    b.HasOne("Trainings.Service.Domain.Coach", "Coach")
                        .WithMany("Groups")
                        .HasForeignKey("CoachId");
                });
#pragma warning restore 612, 618
        }
    }
}
