version: '3.5'

services:
  identity.service:
    image: ${DOCKER_REGISTRY-}identityservice
    container_name: identity-service
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Identity.Service/Dockerfile
    networks:
      - tgp

  players.service:
    image: ${DOCKER_REGISTRY-}playersservice
    container_name: players-service
    ports:
      - 5001:5000
    build:
      context: .
      dockerfile: Players.Service/Dockerfile
    networks:
      - tgp

  trainings.service:
    image: ${DOCKER_REGISTRY-}trainingsservice
    container_name: trainings-service
    ports:
      - 5002:5000
    build:
      context: .
      dockerfile: Trainings.Service/Dockerfile
    networks:
      - tgp

  gamification.service:
    image: ${DOCKER_REGISTRY-}gamificationservice
    container_name: gamification-service
    ports:
      - 5003:5000
    build:
      context: .
      dockerfile: Gamification.Service/Dockerfile
    networks:
      - tgp
    

networks:
  tgp:
    name: tgp


